server:
  port: 8003

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

spring:
  application:
    name: spring-cloud-config-server
  cloud:
     config:
        server:
          git:
            uri: https://github.com/liudgdg/spring-boot-config
            default-label: main
            search-paths: config